// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIT.DepartmentSystem.Web.Data;

#nullable disable

namespace SIT.DepartmentSystem.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427040146_AddMissingApparatusColumns")]
    partial class AddMissingApparatusColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.Apparatus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Agent")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("CostPrice")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Custodian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustodianDepartment")
                        .HasColumnType("text");

                    b.Property<string>("DaysUse")
                        .HasColumnType("text");

                    b.Property<string>("Feature")
                        .HasColumnType("text");

                    b.Property<string>("Imei")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("MaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerNumber")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Os")
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<string>("PartNo")
                        .HasColumnType("text");

                    b.Property<string>("Place")
                        .HasColumnType("text");

                    b.Property<string>("PriceUse")
                        .HasColumnType("text");

                    b.Property<string>("ProcurementStaff")
                        .HasColumnType("text");

                    b.Property<string>("ProductsId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YearsUse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("apparatus", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ApparatusFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApparatusId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadEmp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApparatusId");

                    b.ToTable("apparatus_files", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AdminOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_only");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("text")
                        .HasColumnName("module_code");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_path");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseStandardTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("use_standard_template");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("menu_sections", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleCaseFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_no");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskNo")
                        .HasColumnType("text")
                        .HasColumnName("task_no");

                    b.Property<string>("UploadEmp")
                        .HasColumnType("text")
                        .HasColumnName("upload_emp");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("RecordId");

                    b.HasIndex("TaskId");

                    b.ToTable("module_case_files", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RoutePrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_prefix");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantNote")
                        .HasColumnType("text")
                        .HasColumnName("applicant_note");

                    b.Property<string>("AssignOwner")
                        .HasColumnType("text")
                        .HasColumnName("assign_owner");

                    b.Property<string>("Chipset")
                        .HasColumnType("text")
                        .HasColumnName("chipset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<string>("CustomerProductName")
                        .HasColumnType("text")
                        .HasColumnName("customer_product_name");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DqaOwner")
                        .HasColumnType("text")
                        .HasColumnName("dqa_owner");

                    b.Property<string>("DspModel")
                        .HasColumnType("text")
                        .HasColumnName("dsp_model");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_end_date");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("firmware_version");

                    b.Property<string>("HardwareEngineer")
                        .HasColumnType("text")
                        .HasColumnName("hardware_engineer");

                    b.Property<string>("HardwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("hardware_version");

                    b.Property<string>("JiraLink")
                        .HasColumnType("text")
                        .HasColumnName("jira_link");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MechanicalEngineer")
                        .HasColumnType("text")
                        .HasColumnName("mechanical_engineer");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("NotifyUsers")
                        .HasColumnType("text")
                        .HasColumnName("notify_users");

                    b.Property<string>("Npi")
                        .HasColumnType("text")
                        .HasColumnName("npi");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Pjm")
                        .HasColumnType("text")
                        .HasColumnName("pjm");

                    b.Property<string>("PmSales")
                        .HasColumnType("text")
                        .HasColumnName("pm_sales");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("RecordNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_no");

                    b.Property<string>("RequestApplicant")
                        .HasColumnType("text")
                        .HasColumnName("request_applicant");

                    b.Property<string>("RequestDepartment")
                        .HasColumnType("text")
                        .HasColumnName("request_department");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("SampleMacAddress")
                        .HasColumnType("text")
                        .HasColumnName("sample_mac_address");

                    b.Property<DateOnly?>("SampleReadyDate")
                        .HasColumnType("date")
                        .HasColumnName("sample_ready_date");

                    b.Property<string>("SoftwareEngineer")
                        .HasColumnType("text")
                        .HasColumnName("software_engineer");

                    b.Property<string>("SoftwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("software_version");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubPu")
                        .HasColumnType("text")
                        .HasColumnName("sub_pu");

                    b.Property<string>("Team")
                        .HasColumnType("text")
                        .HasColumnName("team");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtilityVersion")
                        .HasColumnType("text")
                        .HasColumnName("utility_version");

                    b.Property<string>("WirelessDrive")
                        .HasColumnType("text")
                        .HasColumnName("wireless_drive");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("module_records", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BtNo")
                        .HasColumnType("text")
                        .HasColumnName("bt_no");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GcfNo")
                        .HasColumnType("text")
                        .HasColumnName("gcf_no");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PtcrbNo")
                        .HasColumnType("text")
                        .HasColumnName("ptcrb_no");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WifiNo")
                        .HasColumnType("text")
                        .HasColumnName("wifi_no");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("module_record_cases", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignEngineer")
                        .HasColumnType("text")
                        .HasColumnName("assign_engineer");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_end_date");

                    b.Property<string>("Lab")
                        .HasColumnType("text")
                        .HasColumnName("lab");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Quoted")
                        .HasColumnType("text")
                        .HasColumnName("quoted");

                    b.Property<string>("Reimburse")
                        .HasColumnType("text")
                        .HasColumnName("reimburse");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubPu")
                        .HasColumnType("text")
                        .HasColumnName("sub_pu");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("module_record_tasks", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ApparatusFile", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.Apparatus", "Apparatus")
                        .WithMany("Files")
                        .HasForeignKey("ApparatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparatus");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuItem", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.MenuSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleCaseFile", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", "Case")
                        .WithMany("Files")
                        .HasForeignKey("CaseId");

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecord", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecordTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Case");

                    b.Navigation("Record");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecord", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleEntity", "Module")
                        .WithMany("Records")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecord", "Record")
                        .WithMany("Cases")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordTask", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", "Case")
                        .WithMany("Tasks")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.Apparatus", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecord", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
