// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIT.DepartmentSystem.Web.Data;

#nullable disable

namespace SIT.DepartmentSystem.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("verification_application_no_seq");

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.Apparatus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Agent")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("CostPrice")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Custodian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustodianDepartment")
                        .HasColumnType("text");

                    b.Property<string>("DaysUse")
                        .HasColumnType("text");

                    b.Property<string>("Feature")
                        .HasColumnType("text");

                    b.Property<string>("Imei")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("MaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerNumber")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Os")
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<string>("PartNo")
                        .HasColumnType("text");

                    b.Property<string>("Place")
                        .HasColumnType("text");

                    b.Property<string>("PriceUse")
                        .HasColumnType("text");

                    b.Property<string>("ProcurementStaff")
                        .HasColumnType("text");

                    b.Property<string>("ProductsId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YearsUse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("apparatus", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ApparatusFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApparatusId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadEmp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApparatusId");

                    b.ToTable("apparatus_files", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.EquipmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("equipment_groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_groups_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.EquipmentGroupRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAlternative")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_alternative");

                    b.Property<string>("CapabilityTag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("capability_tag");

                    b.Property<Guid>("EquipmentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_group_id");

                    b.Property<string>("PreferredEquipmentId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("preferred_equipment_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentGroupId");

                    b.HasIndex("PreferredEquipmentId");

                    b.ToTable("equipment_group_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_group_requirements_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AdminOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_only");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("text")
                        .HasColumnName("module_code");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_path");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseStandardTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("use_standard_template");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("menu_sections", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleCaseFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_no");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskNo")
                        .HasColumnType("text")
                        .HasColumnName("task_no");

                    b.Property<string>("UploadEmp")
                        .HasColumnType("text")
                        .HasColumnName("upload_emp");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("RecordId");

                    b.HasIndex("TaskId");

                    b.ToTable("module_case_files", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RoutePrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_prefix");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantNote")
                        .HasColumnType("text")
                        .HasColumnName("applicant_note");

                    b.Property<string>("AssignOwner")
                        .HasColumnType("text")
                        .HasColumnName("assign_owner");

                    b.Property<string>("Chipset")
                        .HasColumnType("text")
                        .HasColumnName("chipset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<string>("CustomerProductName")
                        .HasColumnType("text")
                        .HasColumnName("customer_product_name");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DqaOwner")
                        .HasColumnType("text")
                        .HasColumnName("dqa_owner");

                    b.Property<string>("DspModel")
                        .HasColumnType("text")
                        .HasColumnName("dsp_model");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_end_date");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("firmware_version");

                    b.Property<string>("HardwareEngineer")
                        .HasColumnType("text")
                        .HasColumnName("hardware_engineer");

                    b.Property<string>("HardwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("hardware_version");

                    b.Property<string>("JiraLink")
                        .HasColumnType("text")
                        .HasColumnName("jira_link");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MechanicalEngineer")
                        .HasColumnType("text")
                        .HasColumnName("mechanical_engineer");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("NotifyUsers")
                        .HasColumnType("text")
                        .HasColumnName("notify_users");

                    b.Property<string>("Npi")
                        .HasColumnType("text")
                        .HasColumnName("npi");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<string>("Pjm")
                        .HasColumnType("text")
                        .HasColumnName("pjm");

                    b.Property<string>("PmSales")
                        .HasColumnType("text")
                        .HasColumnName("pm_sales");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("RecordNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_no");

                    b.Property<string>("RequestApplicant")
                        .HasColumnType("text")
                        .HasColumnName("request_applicant");

                    b.Property<string>("RequestDepartment")
                        .HasColumnType("text")
                        .HasColumnName("request_department");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("SampleMacAddress")
                        .HasColumnType("text")
                        .HasColumnName("sample_mac_address");

                    b.Property<DateOnly?>("SampleReadyDate")
                        .HasColumnType("date")
                        .HasColumnName("sample_ready_date");

                    b.Property<string>("SoftwareEngineer")
                        .HasColumnType("text")
                        .HasColumnName("software_engineer");

                    b.Property<string>("SoftwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("software_version");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubPu")
                        .HasColumnType("text")
                        .HasColumnName("sub_pu");

                    b.Property<string>("Team")
                        .HasColumnType("text")
                        .HasColumnName("team");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtilityVersion")
                        .HasColumnType("text")
                        .HasColumnName("utility_version");

                    b.Property<string>("WirelessDrive")
                        .HasColumnType("text")
                        .HasColumnName("wireless_drive");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("module_records", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BtNo")
                        .HasColumnType("text")
                        .HasColumnName("bt_no");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GcfNo")
                        .HasColumnType("text")
                        .HasColumnName("gcf_no");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PtcrbNo")
                        .HasColumnType("text")
                        .HasColumnName("ptcrb_no");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WifiNo")
                        .HasColumnType("text")
                        .HasColumnName("wifi_no");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("module_record_cases", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignEngineer")
                        .HasColumnType("text")
                        .HasColumnName("assign_engineer");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_end_date");

                    b.Property<string>("Lab")
                        .HasColumnType("text")
                        .HasColumnName("lab");

                    b.Property<string>("ModelName")
                        .HasColumnType("text")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Quoted")
                        .HasColumnType("text")
                        .HasColumnName("quoted");

                    b.Property<string>("Reimburse")
                        .HasColumnType("text")
                        .HasColumnName("reimburse");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubPu")
                        .HasColumnType("text")
                        .HasColumnName("sub_pu");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("module_record_tasks", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.PlannedTestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EquipmentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_group_id");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<Guid>("ModuleRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_record_id");

                    b.Property<string>("PlanningSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("planning_source");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_template_id");

                    b.Property<string>("ReportTemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_template_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestCapabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_capability_id");

                    b.Property<Guid>("TestEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_environment_id");

                    b.Property<Guid>("TestExecutionProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_execution_profile_id");

                    b.Property<Guid>("TestPlanTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_plan_template_id");

                    b.Property<string>("TestPlanTemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("test_plan_template_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentGroupId");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("TestCapabilityId");

                    b.HasIndex("TestEnvironmentId");

                    b.HasIndex("TestExecutionProfileId");

                    b.HasIndex("TestPlanTemplateId");

                    b.HasIndex("ModuleRecordId", "Status");

                    b.ToTable("planned_test_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_planned_test_items_duration", "estimated_duration_minutes > 0");

                            t.HasCheckConstraint("ck_planned_test_items_source", "planning_source IN ('Agent', 'Manual')");

                            t.HasCheckConstraint("ck_planned_test_items_status", "status IN ('Draft', 'WaitingResource', 'Ready', 'Running', 'Completed', 'Returned', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ReportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ResultSchema")
                        .HasColumnType("text")
                        .HasColumnName("result_schema");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("template_file_path");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("template_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.ToTable("report_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_templates_status", "status IN ('Draft', 'Published', 'Retired')");

                            t.HasCheckConstraint("ck_report_templates_type", "template_type IN ('Excel', 'PDF', 'Other')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Category", "Status");

                    b.ToTable("test_capabilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_capabilities_status", "status IN ('Draft', 'Active', 'Retired')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_mode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("site");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Category", "Status");

                    b.ToTable("test_environments", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_environments_booking_mode", "booking_mode IN ('Exclusive', 'Shared')");

                            t.HasCheckConstraint("ck_test_environments_status", "status IN ('Active', 'Maintenance', 'Disabled')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestExecutionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutomationLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("automation_level");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EquipmentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_group_id");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ReportTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_template_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestCapabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_capability_id");

                    b.Property<Guid>("TestEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_environment_id");

                    b.Property<Guid>("TestPlanTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_plan_template_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EquipmentGroupId");

                    b.HasIndex("ReportTemplateId");

                    b.HasIndex("TestEnvironmentId");

                    b.HasIndex("TestPlanTemplateId");

                    b.HasIndex("TestCapabilityId")
                        .IsUnique()
                        .HasFilter("status = 'Active' AND is_default");

                    b.HasIndex("TestCapabilityId", "Status");

                    b.ToTable("test_execution_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_execution_profiles_automation", "automation_level IN ('Manual', 'SemiAuto', 'Auto')");

                            t.HasCheckConstraint("ck_test_execution_profiles_duration", "estimated_duration_minutes > 0");

                            t.HasCheckConstraint("ck_test_execution_profiles_status", "status IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestPlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_file_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StructuredDefinition")
                        .HasColumnType("text")
                        .HasColumnName("structured_definition");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.ToTable("test_plan_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_plan_templates_status", "status IN ('Draft', 'Published', 'Retired')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LeaderAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("leader_account");

                    b.Property<string>("LeaderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("leader_display_name");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("verification_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_verification_categories_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<string>("ApplicantAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicant_account");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("applicant_email");

                    b.Property<string>("ApplicantExtension")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("applicant_extension");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("applicant_name");

                    b.Property<string>("ApplicationNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("application_no");

                    b.Property<string>("AssignedLeaderAccount")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_leader_account");

                    b.Property<string>("AssignedLeaderDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_leader_display_name");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_name");

                    b.Property<string>("Chipset")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chipset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Customer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("DspModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dsp_model");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("firmware_version");

                    b.Property<string>("HardwareVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hardware_version");

                    b.Property<string>("JiraLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("jira_link");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("ModuleCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_code");

                    b.Property<Guid?>("ModuleRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_record_id");

                    b.Property<string>("Npi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("npi");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("processed_by");

                    b.Property<string>("ProcessingNote")
                        .HasColumnType("text")
                        .HasColumnName("processing_note");

                    b.Property<string>("ProductModel")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_model");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("project_name");

                    b.Property<DateOnly?>("RequestedFinishDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_finish_date");

                    b.Property<string>("SampleMacAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sample_mac_address");

                    b.Property<DateOnly?>("SampleReadyDate")
                        .HasColumnType("date")
                        .HasColumnName("sample_ready_date");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("software_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubPu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sub_pu");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtilityVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("utility_version");

                    b.Property<string>("ValidationRequirement")
                        .HasColumnType("text")
                        .HasColumnName("validation_requirement");

                    b.Property<Guid?>("VerificationCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_category_id");

                    b.Property<string>("WirelessDrive")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("wireless_drive");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationNo")
                        .IsUnique();

                    b.HasIndex("ApplicantAccount", "Status");

                    b.HasIndex("AssignedLeaderAccount", "Status");

                    b.HasIndex("ModuleRecordId")
                        .IsUnique()
                        .HasFilter("module_record_id IS NOT NULL");

                    b.HasIndex("Status", "SubmittedAt");

                    b.HasIndex("VerificationCategoryId", "Status");

                    b.ToTable("verification_applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_verification_applications_status", "status IN ('Draft', 'Submitted', 'Returned', 'Accepted', 'Rejected')");
                        });
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationApplicationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid>("VerificationApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_application_id");

                    b.HasKey("Id");

                    b.HasIndex("VerificationApplicationId");

                    b.ToTable("verification_application_files", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ApparatusFile", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.Apparatus", "Apparatus")
                        .WithMany("Files")
                        .HasForeignKey("ApparatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apparatus");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.EquipmentGroupRequirement", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.EquipmentGroup", "EquipmentGroup")
                        .WithMany("Requirements")
                        .HasForeignKey("EquipmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.Apparatus", "PreferredEquipment")
                        .WithMany()
                        .HasForeignKey("PreferredEquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentGroup");

                    b.Navigation("PreferredEquipment");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuItem", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.MenuSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleCaseFile", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", "Case")
                        .WithMany("Files")
                        .HasForeignKey("CaseId");

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecord", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecordTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Case");

                    b.Navigation("Record");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecord", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleEntity", "Module")
                        .WithMany("Records")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecord", "Record")
                        .WithMany("Cases")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordTask", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", "Case")
                        .WithMany("Tasks")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.PlannedTestItem", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.EquipmentGroup", "EquipmentGroup")
                        .WithMany("PlannedTestItems")
                        .HasForeignKey("EquipmentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecord", "ModuleRecord")
                        .WithMany()
                        .HasForeignKey("ModuleRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany("PlannedTestItems")
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestCapability", "TestCapability")
                        .WithMany("PlannedTestItems")
                        .HasForeignKey("TestCapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestEnvironment", "TestEnvironment")
                        .WithMany("PlannedTestItems")
                        .HasForeignKey("TestEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestExecutionProfile", "TestExecutionProfile")
                        .WithMany("PlannedTestItems")
                        .HasForeignKey("TestExecutionProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestPlanTemplate", "TestPlanTemplate")
                        .WithMany("PlannedTestItems")
                        .HasForeignKey("TestPlanTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentGroup");

                    b.Navigation("ModuleRecord");

                    b.Navigation("ReportTemplate");

                    b.Navigation("TestCapability");

                    b.Navigation("TestEnvironment");

                    b.Navigation("TestExecutionProfile");

                    b.Navigation("TestPlanTemplate");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestExecutionProfile", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.EquipmentGroup", "EquipmentGroup")
                        .WithMany("ExecutionProfiles")
                        .HasForeignKey("EquipmentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ReportTemplate", "ReportTemplate")
                        .WithMany("ExecutionProfiles")
                        .HasForeignKey("ReportTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestCapability", "TestCapability")
                        .WithMany("ExecutionProfiles")
                        .HasForeignKey("TestCapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestEnvironment", "TestEnvironment")
                        .WithMany("ExecutionProfiles")
                        .HasForeignKey("TestEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.TestPlanTemplate", "TestPlanTemplate")
                        .WithMany("ExecutionProfiles")
                        .HasForeignKey("TestPlanTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentGroup");

                    b.Navigation("ReportTemplate");

                    b.Navigation("TestCapability");

                    b.Navigation("TestEnvironment");

                    b.Navigation("TestPlanTemplate");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationApplication", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.ModuleRecord", "ModuleRecord")
                        .WithOne()
                        .HasForeignKey("SIT.DepartmentSystem.Web.Entities.VerificationApplication", "ModuleRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIT.DepartmentSystem.Web.Entities.VerificationCategory", "VerificationCategory")
                        .WithMany("Applications")
                        .HasForeignKey("VerificationCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ModuleRecord");

                    b.Navigation("VerificationCategory");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationApplicationFile", b =>
                {
                    b.HasOne("SIT.DepartmentSystem.Web.Entities.VerificationApplication", "VerificationApplication")
                        .WithMany("Files")
                        .HasForeignKey("VerificationApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationApplication");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.Apparatus", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.EquipmentGroup", b =>
                {
                    b.Navigation("ExecutionProfiles");

                    b.Navigation("PlannedTestItems");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.MenuSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecord", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ModuleRecordCase", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.ReportTemplate", b =>
                {
                    b.Navigation("ExecutionProfiles");

                    b.Navigation("PlannedTestItems");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestCapability", b =>
                {
                    b.Navigation("ExecutionProfiles");

                    b.Navigation("PlannedTestItems");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestEnvironment", b =>
                {
                    b.Navigation("ExecutionProfiles");

                    b.Navigation("PlannedTestItems");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestExecutionProfile", b =>
                {
                    b.Navigation("PlannedTestItems");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.TestPlanTemplate", b =>
                {
                    b.Navigation("ExecutionProfiles");

                    b.Navigation("PlannedTestItems");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationApplication", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("SIT.DepartmentSystem.Web.Entities.VerificationCategory", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
